version: '3.7'
services:
  pg:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next-saas
    ports:
      - '5432:5432'
